<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,17,1,'5Lqn5ZOB');
$cfg_Cs[2]=array(1,17,1,'5Y+R54Ot57O75YiX');
$cfg_Cs[3]=array(1,17,1,'5Y+R54Ot57O75YiX5YWD5Lu2');
$cfg_Cs[4]=array(1,17,1,'5Y+R54Ot5Lqn5ZOB');
$cfg_Cs[5]=array(0,1,1,'5YWs5Y+45LuL57uN');
$cfg_Cs[6]=array(0,1,0,'5YWs5Y+45Yqo5oCB');
$cfg_Cs[7]=array(6,1,0,'5YWs5Y+45paw6Ze7');
$cfg_Cs[8]=array(6,1,0,'6KGM5Lia5paw6Ze7');
$cfg_Cs[9]=array(6,1,0,'5aqS5L2T5paw6Ze7');
$cfg_Cs[10]=array(0,1,0,'6IGU57O75oiR5Lus');
$cfg_Cs[14]=array(5,1,1,'5YWz5LqO54Ov54mb');
$cfg_Cs[31]=array(0,-18,0,'5rWP6KeI5pWw5o2u');
$cfg_Cs[29]=array(5,1,0,'5oiR5Lus55qE5Zui6Zif');
?>