<?php
$z[0]=Array("arcurl","",149,164);
$z[0][4]=array();
$z[1]=Array("typeid","",166,215);
$z[1][4]=array();
$z[1][4]['function']="mygetretype(@me,typeurl)";
$z[2]=Array("litpic","",251,266);
$z[2][4]=array();
$z[3]=Array("description","",273,320);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,50)";
$z[4]=Array("title","",409,423);
$z[4][4]=array();
$z[5]=Array("description","",503,551);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,100)";

?>