<?php
$z[0]=Array("litpic","",206,221);
$z[0][4]=array();
$z[1]=Array("global","",451,481);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[2]=Array("global","",958,988);
$z[2][4]=array();
$z[2][4]['name']="autoindex";
$z[3]=Array("title","",990,1004);
$z[3][4]=array();
$z[4]=Array("global","",1284,1314);
$z[4][4]=array();
$z[4][4]['name']="autoindex";
$z[5]=Array("title","",1938,1952);
$z[5][4]=array();

?>