
<field:name itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="您的电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="您的邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:theme itemname="您的标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:theme>

<field:message itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:message>


<field:time itemname="时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:time>
