<table class="table table-hover">
                            <thead>
                                <tr>
                                    <td>经销商</td>
                                    <td>电话</td>
                                    <td>邮箱</td>
                                    <td>地址</td>
                                </tr>
                            </thead>
                                <tr><td></td><td></td></tr>
                              </table>
                        <p class="list-content">
                            <a href="[field:arcurl/]">
                                <i class="icon-tag"></i>
                                [field:title/][field:linkman/]</a>
                            [field:email/]
                            <span>[field:pubdate function=MyDate('Y-m-d',@me)/]</span>
                        </p>