<div class="col-md-4 text-center animate-box list-product">
                                <div class="product">
                                    <div class="product-grid" style="background-image:url([field:litpic/]);">
                                        <div class="inner">
                                            <p>
                                                <a href="#" class="icon" data-toggle="modal" data-target="#myModal">
                                                    <i class="icon-eye"></i>
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="desc">
                                        <h3>
                                            <a href="#" data-toggle="modal" data-target="#myModal">[field:title/]</a>
                                        </h3>
                                    </div>
                                </div>
                            </div>