{dede:pagestyle maxwidth='1920' pagepicnum='12' ddmaxwidth='1920' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q02922.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q02922.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q02937.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q02937.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q02938.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q02938.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q03024.jpg' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q03024.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q03047.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q03047.png {/dede:img}
