<field:slide itemname="幻灯大图" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:slide>
<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>
<field:title_1 itemname="介绍标题" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:title_1>
<field:body itemname="介绍内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="5000" page="">
</field:body>
<field:title_2 itemname="参数标题" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:title_2>
<field:body2 itemname="参数内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="5000" page="">
</field:body2>
<field:bigpic itemname="首页幻灯图" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bigpic>