<div class="col-md-4 text-center animate-box list-product">
                                <div class="product">
                                    <div class="product-grid" style="background-image:url([field:litpic/]);">
                                        <div class="inner">
                                            <p>
                                                <a href="#" class="icon" data-toggle="modal" data-target="#myModal[field:global name=autoindex/]" data-target=".bs-example-modal-lg">
                                                    <i class="icon-eye"></i>
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="desc">
                                        <h3>
                                            <a href="#" data-toggle="modal" data-target="#myModal[field:global name=autoindex/]" data-target=".bs-example-modal-lg">[field:title/]</a>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                            <!-- Modal -->
                            <div class="modal fade" id="myModal[field:global name=autoindex/]" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            <h4 class="modal-title" id="myModalLabel">[field:title/]</h4>
                                        </div>
                                        <div class="modal-body">
                                            [field:body/]
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                            <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                                        </div>
                                    </div>
                                </div>
                            </div>