<table class="table table-hover">
                                <td><tr><td></td><td></td></tr></td>
                              </table>
                        <p class="list-content">
                            <a href="[field:arcurl/]">
                                <i class="icon-tag"></i>
                                [field:title/][field:linkman/]</a>
                            [field:email/]
                            <span>[field:pubdate function=MyDate('Y-m-d',@me)/]</span>
                        </p>