{dede:pagestyle maxwidth='1920' pagepicnum='12' ddmaxwidth='1920' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q02401.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q02401.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q02402.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q02402.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q02406.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q02406.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12Q02407.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12Q02407.png {/dede:img}
{dede:img ddimg='/uploads/allimg/180113/1-1P113155019.png' text='' width='800' height='800'} /uploads/allimg/180113/1-1P113155019.png {/dede:img}
