<a href="[field:arcurl/]"><img src="[field:slide function=GetImgUrl(@me)/]" alt="[field:title/]" /></a>
      <div class="fh5co-dynamic-main" style="background-image:url('[field:bigpic function=GetImgUrl(@me)/]');">
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
              <h2>[field:title/]
                <span>[field:typenamedir/]</span>
              </h2>
            </div>
            <div class="col-md-12 hot-product"></div>
          </div>
        </div>
      </div>