<?php
$z[0]=Array("typeid","",149,198);
$z[0][4]=array();
$z[0][4]['function']="mygetretype(@me,typeurl)";
$z[1]=Array("litpic","",236,251);
$z[1][4]=array();
$z[2]=Array("description","",258,305);
$z[2][4]=array();
$z[2][4]['function']="cn_substr(@me,50)";
$z[3]=Array("title","",394,408);
$z[3][4]=array();
$z[4]=Array("description","",488,536);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,100)";

?>