<?php
$z[0]=Array("pagestyle","",0,93);
$z[0][4]=array();
$z[0][4]['maxwidth']="1920";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="1920";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/171130/1-1G130144F7.png ",95,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171130/1-1G130144F7.png";
$z[1][4]['text']="";
$z[1][4]['width']="1366";
$z[1][4]['height']="911";
$z[2]=Array("img"," /uploads/allimg/171130/1-1G130144F9.png ",241,385);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171130/1-1G130144F9.png";
$z[2][4]['text']="";
$z[2][4]['width']="1366";
$z[2][4]['height']="911";
$z[3]=Array("img"," /uploads/allimg/171130/1-1G130144G0.png ",387,531);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171130/1-1G130144G0.png";
$z[3][4]['text']="";
$z[3][4]['width']="1366";
$z[3][4]['height']="911";

?>