{dede:pagestyle maxwidth='1920' pagepicnum='12' ddmaxwidth='1920' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/171130/1-1G130144F7.png' text='' width='1366' height='911'} /uploads/allimg/171130/1-1G130144F7.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171130/1-1G130144F9.png' text='' width='1366' height='911'} /uploads/allimg/171130/1-1G130144F9.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171130/1-1G130144G0.png' text='' width='1366' height='911'} /uploads/allimg/171130/1-1G130144G0.png {/dede:img}
