<div class="owl-carousel">
            <div class="item">
              <div class="thumbnail">
                <a href="#">
                  <img src="assets/images/portfolio/img1.jpg" alt="">
                </a>
              </div>
              <div class="caption">
                <h4>石墨烯电采暖炉</h4>
                <!-- <p>节能速热电暖炉，以电力为能源，以水为导热介质，通过石墨烯复合材料快速电发热技术，高效地将电能转化为热能，电热转换效率可高达99%。</p> -->
                <a class="btn btn-mini" href="#">了解更多</a>
              </div>
            </div>
          </div>
          <!-- <div class="col-md-4 text-center animate-box">
            <div class="product">
              <div class="product-grid" style="background-image:url([field:litpic/]);background-position:center;">
                <div class="inner">
                  <p>
                    <a href="[field:arcurl/]" class="icon">
                      <i class="icon-eye"></i>
                    </a>
                  </p>
                </div>
              </div>
              <div class="desc">
                <h3>
                  <a href="[field:arcurl/]">[field:title/]</a>
                </h3>
              </div>
            </div>
          </div> -->