{dede:pagestyle maxwidth='1920' pagepicnum='12' ddmaxwidth='1920' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/171128/1-1G12PQR3.png' text='' width='1920' height='1280'} /uploads/allimg/171128/1-1G12PQR3.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12PQR4.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12PQR4.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171128/1-1G12PQR5.png' text='' width='1366' height='911'} /uploads/allimg/171128/1-1G12PQR5.png {/dede:img}
{dede:img ddimg='/uploads/allimg/171130/1-1G130141Q2.png' text='' width='678' height='434'} /uploads/allimg/171130/1-1G130141Q2.png {/dede:img}
