<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/171128/1-1G12PPK3.png ",93,234);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171128/1-1G12PPK3.png";
$z[1][4]['text']="";
$z[1][4]['width']="1920";
$z[1][4]['height']="1080";
$z[2]=Array("img"," /uploads/allimg/171128/1-1G12PPK4.png ",236,377);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171128/1-1G12PPK4.png";
$z[2][4]['text']="";
$z[2][4]['width']="1920";
$z[2][4]['height']="1080";

?>