<p>
                            <b>省份：</b>[field:linkallplace/]
                        </p>
                        <p>
                            <b>市级：</b>[field:nativeplace /]
                            <select>
                                <option value ="[field:nativeplace /]"></option>
                            </select>
                        </p>
                        <!-- <p>
                            <b>地区：</b>[field:county /]
                        </p> -->