<?php
$z[0]=Array("field","",42,63);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",65,87);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","global \$dsql;\$sql = \"SELECT id From `#@__arctype` WHERE reid=' @me\r\n						    ' And ishidden<>1 order by sortrank asc limit 0,1\";\$row = \$dsql->GetOne(\$sql);@me=is_array(\$row)?'dropdown ':'none ';",112,355);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n							<li>\r\n								<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n							</li>\r\n							",375,519);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>