<item>
    <title><![CDATA[[field:title/]]]></title>
    <link>[field:fullurl/]</link>
    <description><![CDATA[[field:description function='html2text(@me)'/]...<br /><b>文章分类</b>:<a href="[field:typeurl/]" target="_blank">[field:typename/]</a><br /><a href="[field:arcurl/]" target="_blank">阅读全文</a>]]></description>
    <pubDate>[field:stime/]</pubDate>
    <category>[field:typename/]</category>
    <author>[field:writer/]</author>
    <comments>[field:source/]</comments>
</item>