<?php
$z[0]=Array("pagestyle","",0,93);
$z[0][4]=array();
$z[0][4]['maxwidth']="1920";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="1920";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/171128/1-1G12Q02401.png ",95,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171128/1-1G12Q02401.png";
$z[1][4]['text']="";
$z[1][4]['width']="1366";
$z[1][4]['height']="911";
$z[2]=Array("img"," /uploads/allimg/171128/1-1G12Q02402.png ",241,385);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171128/1-1G12Q02402.png";
$z[2][4]['text']="";
$z[2][4]['width']="1366";
$z[2][4]['height']="911";
$z[3]=Array("img"," /uploads/allimg/171128/1-1G12Q02406.png ",387,531);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171128/1-1G12Q02406.png";
$z[3][4]['text']="";
$z[3][4]['width']="1366";
$z[3][4]['height']="911";
$z[4]=Array("img"," /uploads/allimg/171128/1-1G12Q02407.png ",533,677);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/171128/1-1G12Q02407.png";
$z[4][4]['text']="";
$z[4][4]['width']="1366";
$z[4][4]['height']="911";

?>