<?php
$z[0]=Array("arcurl","",149,164);
$z[0][4]=array();
$z[1]=Array("typeid","",166,214);
$z[1][4]=array();
$z[1][4]['function']="mygetretype(@me,arcurl)";
$z[2]=Array("litpic","",250,265);
$z[2][4]=array();
$z[3]=Array("description","",272,319);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,50)";
$z[4]=Array("title","",408,422);
$z[4][4]=array();
$z[5]=Array("description","",502,550);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,100)";

?>