<?php
$z[0]=Array("arcurl","",149,164);
$z[0][4]=array();
$z[1]=Array("typeid","",166,216);
$z[1][4]=array();
$z[1][4]['function']="mygetretype(@me,typename)";
$z[2]=Array("litpic","",252,267);
$z[2][4]=array();
$z[3]=Array("description","",274,321);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,50)";
$z[4]=Array("title","",410,424);
$z[4][4]=array();
$z[5]=Array("description","",504,552);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,100)";

?>