<?php
$z[0]=Array("global","",10,37);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("field","",37,65);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","@me=date('Y-m-d');",80,150);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n <url><loc>[field:global.cfg_basehost /][field:typelink/]</loc><lastmod>[field:typeid runphp='yes']@me=date('Y-m-d');[/field:typeid]</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url>\r\n",222,479);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['row']="1000";

?>