<url><loc>{dede:global.cfg_basehost/}{dede:field name='typeurl'/}</loc><lastmod>{dede:field name='typeid' runphp='yes'}@me=date('Y-m-d');{/dede:field}</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url>
{dede:channel type='son' row='1000'}
 <url><loc>[field:global.cfg_basehost /][field:typelink/]</loc><lastmod>[field:typeid runphp='yes']@me=date('Y-m-d');[/field:typeid]</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url>
{/dede:channel}