<?php
$z[0]=Array("pagestyle","",0,93);
$z[0][4]=array();
$z[0][4]['maxwidth']="1920";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="1920";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/171130/1-1G130144510.png ",95,202);
$z[1][4]=array();
$z[1][4]['ddimg']="";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="1024";
$z[2]=Array("img"," /uploads/allimg/171130/1-1G130144513.png ",204,309);
$z[2][4]=array();
$z[2][4]['ddimg']="";
$z[2][4]['text']="";
$z[2][4]['width']="500";
$z[2][4]['height']="500";
$z[3]=Array("img"," /uploads/allimg/171130/1-1G130144531.png ",311,416);
$z[3][4]=array();
$z[3][4]['ddimg']="";
$z[3][4]['text']="";
$z[3][4]['width']="500";
$z[3][4]['height']="500";

?>