<div class="item">
                  <div class="testimony-slide active text-center">
                    <figure>
                      <a href="[field:arcurl/]">
                        <img src="[field:litpic/]" alt="[field:description function=cn_substr(@me,50)/]">
                      </a>
                    </figure>
                    <span>[field:title/]</span>
                    <blockquote>
                      <!-- <p>&ldquo;[field:description function=cn_substr(@me,100)/].&rdquo;</p> -->
                    </blockquote>
                  </div>
                </div>