<div class="col-md-4 text-center animate-box">
                        <div class="product">
                            <div class="product-grid" style="background-image:url([field:litpic/]);">
                                <div class="inner">
                                    <p>
                                        <a href="[field:arcurl/]" class="icon">
                                            <i class="icon-eye"></i>
                                        </a>
                                    </p>
                                </div>
                            </div>
                            <div class="desc">
                                <h3>
                                    <a href="[field:arcurl/]">[field:typename/]</a>
                                </h3>
                            </div>
                        </div>
                    </div>