<li style="background-image: url('[field:bigpic function=GetImgUrl(@me)/]');"> -->
          {dede:myppt typeid=1 row=4}[field:url/][field:pic/][field:pic2/][field:title/]
            <li style="background-image: url('[field:pic/]');">
            <!-- <div class="overlay-gradient"></div> -->
            <!-- <div class="container">
              <div class="col-md-6 col-md-offset-3 col-md-pull-3 js-fullheight slider-text">
                <div class="slider-text-inner">
                  <div class="desc">
                    <h2>[field:title/]</h2>
                    <p>[field:description function=cn_substr(@me,150)/]...</p>
                    <p>
                      <a href="[field:arcurl/]" class="btn btn-primary btn-outline btn-lg">了解更多</a>
                    </p>
                  </div>
                </div>
              </div>
            </div> -->
          </li>
          {/dede:myppt}
          <!--