<li style="background-image: url('[field:slide/]');">
            <!-- <div class="overlay-gradient"></div> -->
            <div class="container">
              <div class="col-md-6 col-md-offset-3 col-md-pull-3 js-fullheight slider-text">
                <div class="slider-text-inner">
                  <div class="desc">
                    <h2>[field:title/]</h2>
                    <p>[field:description function=cn_substr(@me,150)/]...</p>
                    <p>
                      <a href="[field:arcurl/]" class="btn btn-primary btn-outline btn-lg">了解更多</a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </li>