<?php
$z[0]=Array("arcurl","",9,24);
$z[0][4]=array();
$z[1]=Array("slide","",36,74);
$z[1][4]=array();
$z[1][4]['function']="GetImgUrl(@me)";
$z[2]=Array("title","",81,95);
$z[2][4]=array();
$z[3]=Array("slide","",172,187);
$z[3][4]=array();
$z[4]=Array("title","",352,366);
$z[4][4]=array();
$z[5]=Array("typenamedir","",390,410);
$z[5][4]=array();
$z[6]=Array("body2","",507,522);
$z[6][4]=array();

?>