<?php
$z[0]=Array("global","",195,221);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",263,290);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",330,360);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",1626,1661);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("type","[field:typelitpic/]",1770,1820);
$z[4][4]=array();
$z[4][4]['typeid']="";
$z[5]=Array("type","[field:typeurl/]",2040,2089);
$z[5][4]=array();
$z[5][4]['typeid']="10";
$z[6]=Array("type","\r\n								<h1>[field:typenamedir/]</h1>\r\n								<h2>[field:typename/]</h2>\r\n								",2205,2321);
$z[6][4]=array();
$z[6][4]['typeid']="";
$z[7]=Array("type","\r\n						<div class=\"col-md-12\">\r\n							<div class=\"desc\">\r\n								<p>[field:content/]</p>\r\n							</div>\r\n						</div>\r\n						",2550,2709);
$z[7][4]=array();
$z[7][4]['typeid']="";
$z[8]=Array("include","",2763,2800);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";
$z[9]=Array("include","",3482,3525);
$z[9][4]=array();
$z[9][4]['filename']="zidongzhuaqu.htm";

?>