<?php
$z[0]=Array("arclist","\r\n<item>\r\n    <title><![CDATA[[field:title/]]]></title>\r\n    <link>[field:fullurl/]</link>\r\n    <description><![CDATA[[field:description function='html2text(@me)'/]...<br /><b>文章分类</b>:<a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a><br /><a href=\"[field:arcurl/]\" target=\"_blank\">阅读全文</a>]]></description>\r\n    <pubDate>[field:stime/]</pubDate>\r\n    <category>[field:typename/]</category>\r\n    <author>[field:writer/]</author>\r\n    <comments>[field:source/]</comments>\r\n</item>\r\n",72,634);
$z[0][4]=array();
$z[0][4]['typeid']="0";
$z[0][4]['row']="200";

?>