<?php
$z[0]=Array("arclist"," \r\n<url><loc>[field:global.cfg_basehost /][field:arcurl/]</loc><lastmod>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url>\r\n",101,343);
$z[0][4]=array();
$z[0][4]['typeid']="0";
$z[0][4]['row']="1000";
$z[1]=Array("channelartlist","\r\n<url><loc>{dede:global.cfg_basehost/}{dede:field name='typeurl'/}</loc><lastmod>{dede:field name='typeid' runphp='yes'}@me=date('Y-m-d');{/dede:field}</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url>\r\n{dede:channel type='son' row='1000'}\r\n <url><loc>[field:global.cfg_basehost /][field:typelink/]</loc><lastmod>[field:typeid runphp='yes']@me=date('Y-m-d');[/field:typeid]</lastmod><changefreq>daily</changefreq><priority>1.0</priority></url>\r\n{/dede:channel}\r\n",345,880);
$z[1][4]=array();
$z[1][4]['row']="1000";

?>