<?php  exit();
/*
Page: /install/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-01-06 16:24:03
*/
?>
<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-01-06 16:24:15
*/
?>
<?php  exit();
/*
Page: /install/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-01-06 16:24:38
*/
?>
<?php  exit();
/*
Page: /install/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-01-06 16:24:57
*/
?>
